image: Visual Studio 2019
shallow_clone: true
skip_tags: true

version: 1.0.0.{build}-alpha

branches:
  only:
    - master

only_commits:
  files:
    - 'ModMyFactory.WebApi\'

skip_commits:
  files:
    - '**\*.yml'

build_script:
  - dotnet build ModMyFactory.WebApi\ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%

after_build:
  - dotnet pack ModMyFactory.WebApi\ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%

cache:
  - '%userprofile%\.nuget\packages'
  - '%LocalAppData%\NuGet\v3-cache'

artifacts:
  path: '**\*.nupkg'
  name: Packages

deploy:
- provider: NuGet
  api_key:
    secure: KA2qkfEDg1TjBRCavKySQnRwcN7h+QZN/IaUM8TTBkWiQUuCs9o28hAVBd/o++q6
  artifact: 'Packages'