image: Visual Studio 2022
shallow_clone: true
skip_non_tags: true

version: 4.3.3.{build}-beta

branches:
  only:
    - master

environment:
  OAUTH_TOKEN:
    secure: oFSYhDRIY5Qd7D+Cn7eEO6MpwzeYkR0FPok/zoWZ8rTFpMbMyvnUN6vTKzWAG09Q
    
build_script:
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\linux-x64\ -c Release -f net6.0 -r linux-x64 --self-contained=true --version-suffix %APPVEYOR_BUILD_VERSION% -p:OauthToken=%OAUTH_TOKEN%
# - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\osx-x64\ -c Release -f net6.0 -r osx-x64 --self-contained=true --version-suffix %APPVEYOR_BUILD_VERSION% -p:OauthToken=%OAUTH_TOKEN%
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\win-x64\ -c Release -f net6.0 -r win-x64 --self-contained=true --version-suffix %APPVEYOR_BUILD_VERSION% -p:OauthToken=%OAUTH_TOKEN%
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\net6.0\ -c Release -f net6.0 --version-suffix %APPVEYOR_BUILD_VERSION% -p:OauthToken=%OAUTH_TOKEN%
  
after_build:
  - 7z a %APPVEYOR_BUILD_VERSION%_linux64.zip .\ModMyFactoryGUI\bin\publish\linux-x64\*
# - 7z a %APPVEYOR_BUILD_VERSION%_osx.zip .\ModMyFactoryGUI\bin\publish\osx-x64\*
  - 7z a %APPVEYOR_BUILD_VERSION%_win64.zip .\ModMyFactoryGUI\bin\publish\win-x64\*
  - 7z a %APPVEYOR_BUILD_VERSION%_universal.zip .\ModMyFactoryGUI\bin\publish\net6.0\*

artifacts:
  - path: '%APPVEYOR_BUILD_VERSION%_*.zip'
    name: Binaries

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: 'ModMyFactoryGUI v$(appveyor_build_version)'
  description: ''
  auth_token:
    secure: ygEi7xyaY9+27XwXdXkp1F+Gq8V/N9EGo7Uj6Arn+LydKBYK2R0ksYYZWfs9ObRJ
  artifact: Binaries
  prerelease: true # don't forget to change