image: Visual Studio 2019
shallow_clone: true
skip_non_tags: true

version: 1.0.0.{build}-alpha

branches:
  only:
    - master

skip_commits:
  files:
    - '**\*.yml'

build_script:
  - dotnet publish ModMyFactoryGUI\ -c Release -f netcoreapp3.0 --version-suffix %APPVEYOR_BUILD_VERSION%
  - dotnet publish ModMyFactoryGUI\ -c Release -f net472 --version-suffix %APPVEYOR_BUILD_VERSION%

after_build:
  - 7z a mmf_%APPVEYOR_BUILD_VERSION%_netcoreapp3.0.zip .\ModMyFactoryGUI\bin\Release\netcoreapp3.0\publish\*
  - 7z a mmf_%APPVEYOR_BUILD_VERSION%_net472.zip .\ModMyFactoryGUI\bin\Release\net472\publish\*

cache:
  - '%userprofile%\.nuget\packages'
  - '%LocalAppData%\NuGet\v3-cache'

artifacts:
  path: mmf_%APPVEYOR_BUILD_VERSION%_*.zip
  name: Binaries

#deploy:
#- provider: