image: Visual Studio 2019
shallow_clone: true
skip_non_tags: true

version: 4.2.4.{build}-beta

branches:
  only:
    - master
    
build_script:
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\linux-x64\ -c Release -f net5.0 -r linux-x64 -p:PublishTrimmed=true --version-suffix %APPVEYOR_BUILD_VERSION%
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\osx-x64\ -c Release -f net5.0 -r osx-x64 -p:PublishTrimmed=true --version-suffix %APPVEYOR_BUILD_VERSION%
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\win-x64\ -c Release -f net5.0 -r win-x64 -p:PublishTrimmed=true --version-suffix %APPVEYOR_BUILD_VERSION%
  - dotnet publish ModMyFactoryGUI\ -o ModMyFactoryGUI\bin\publish\net5.0\ -c Release -f net5.0 --version-suffix %APPVEYOR_BUILD_VERSION%
  
after_build:
  - 7z a %APPVEYOR_BUILD_VERSION%_linux64.zip .\ModMyFactoryGUI\bin\publish\linux-x64\*
  - 7z a %APPVEYOR_BUILD_VERSION%_osx.zip .\ModMyFactoryGUI\bin\publish\osx-x64\*
  - 7z a %APPVEYOR_BUILD_VERSION%_win64.zip .\ModMyFactoryGUI\bin\publish\win-x64\*
  - 7z a %APPVEYOR_BUILD_VERSION%_universal.zip .\ModMyFactoryGUI\bin\publish\net5.0\*

artifacts:
  - path: '%APPVEYOR_BUILD_VERSION%_*.zip'
    name: Binaries

deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  release: 'ModMyFactoryGUI v$(appveyor_build_version)'
  description: ''
  auth_token:
    secure: pvpw2TIwvV+P7KoIG1vAJCBT8aSYCVzgtp9Cq+IsyQ/wsmgXbSzJsg9uYPsD8ZCX
  artifact: Binaries
  prerelease: true # don't forget to change