image: Visual Studio 2019
shallow_clone: true
skip_tags: true

version: 1.2.0.{build}-alpha

branches:
  only:
    - master

only_commits:
  files:
    - 'ModMyFactory.Export\'

skip_commits:
  files:
    - '**\*.yml'

install:
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
  - ps: '& $env:temp\dotnet-install.ps1 -Architecture x64 -InstallDir "$env:ProgramFiles\dotnet"'

build_script:
  - dotnet build ModMyFactory.Export\ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%

after_build:
  - dotnet pack ModMyFactory.Export\ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg

cache:
  - '%userprofile%\.nuget\packages'
  - '%LocalAppData%\NuGet\v3-cache'

artifacts:
  - path: '**\*.nupkg'
    name: Packages
  - path: '**\*.snupkg'
    name: Symbols

deploy:
  - provider: NuGet
    api_key:
      secure: KA2qkfEDg1TjBRCavKySQnRwcN7h+QZN/IaUM8TTBkWiQUuCs9o28hAVBd/o++q6
    artifact: 'Packages'
  - provider: NuGet
    api_key:
      secure: KA2qkfEDg1TjBRCavKySQnRwcN7h+QZN/IaUM8TTBkWiQUuCs9o28hAVBd/o++q6
    artifact: 'Symbols'