image: Visual Studio 2019
shallow_clone: true
skip_tags: true

version: 1.1.0.{build}-alpha

branches:
  only:
    - master

only_commits:
  files:
    - 'ModMyFactory.Server\'

skip_commits:
  files:
    - '**\*.yml'
    
install:
  - ps: Invoke-WebRequest -Uri 'https://dot.net/v1/dotnet-install.ps1' -UseBasicParsing -OutFile "$env:temp\dotnet-install.ps1"
  - ps: '& $env:temp\dotnet-install.ps1 -Architecture x64 -InstallDir "$env:ProgramFiles\dotnet"'

build_script:
  - dotnet build ModMyFactory.Server\ -c Release --version-suffix %APPVEYOR_BUILD_VERSION%

after_build:
  - dotnet pack ModMyFactory.Server\ -c Release --version-suffix %APPVEYOR_BUILD_VERSION% --no-build --include-symbols -p:SymbolPackageFormat=snupkg

artifacts:
  - path: '**\*.nupkg'
    name: Packages
  - path: '**\*.snupkg'
    name: Symbols

deploy:
  - provider: NuGet
    api_key:
      secure: iv9Dyc9qD5/UhCjimUN8wwpRaXTd1eGuSFTW28A/fjjyn8wJKlN96iSFvxevYGG0
    artifact: 'Packages'
  - provider: NuGet
    api_key:
      secure: iv9Dyc9qD5/UhCjimUN8wwpRaXTd1eGuSFTW28A/fjjyn8wJKlN96iSFvxevYGG0
    artifact: 'Symbols'